# Generated by Django 5.1 on 2024-08-29 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.CharField(max_length=100, verbose_name='Ткань')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Ткань',
                'verbose_name_plural': 'Ткани',
            },
        ),
        migrations.CreateModel(
            name='Goods_Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation', models.CharField(max_length=100, verbose_name='Установка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Установка',
                'verbose_name_plural': 'Установка',
            },
        ),
        migrations.CreateModel(
            name='Goods_Quadrature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quadrature', models.CharField(max_length=100, verbose_name='Квадратура')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Квадратура',
                'verbose_name_plural': 'Квадратура',
            },
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric1', to='calculator.goods_fabric')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric3', to='calculator.goods_installation')),
                ('quadrature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric2', to='calculator.goods_quadrature')),
            ],
        ),
    ]
