# Generated by Django 5.1 on 2024-08-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=100, verbose_name='Оплата')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплата',
            },
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='installation',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='quadrature',
        ),
        migrations.DeleteModel(
            name='Goods_Installation',
        ),
        migrations.DeleteModel(
            name='Calculation',
        ),
        migrations.DeleteModel(
            name='Goods_Quadrature',
        ),
    ]
